### ISSUE TITLE
Build for AoT fails

### ISSUE THREAD

**Issue by AmitMY** [willsoto/angular2-chartist#98]
I'm using Ionic, which has a `build` script that builds the application for production use using AOT compilation.

This is the error I am getting:
> [21:35:00]  build prod failed: Unexpected value 'ChartistModule' imported by the module 'AppModule' 

And this is the stack:
> [21:35:00]  Error: Unexpected value 'ChartistModule' imported by the module 'AppModule' 
Error: Unexpected value 'ChartistModule' imported by the module 'AppModule'
    at D:\xampp\htdocs\qzzy\node_modules\@angular\compiler\bundles\compiler.umd.js:14675:33
    at Array.forEach (native)
    at CompileMetadataResolver._loadNgModuleMetadata (D:\xampp\htdocs\qzzy\node_modules\@angular\compiler\bundles\compiler.umd.js:14660:51)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (D:\xampp\htdocs\qzzy\node_modules\@angular\compiler\bundles\compiler.umd.js:14636:23)
    at addNgModule (D:\xampp\htdocs\qzzy\node_modules\@angular\compiler\bundles\compiler.umd.js:12944:43)
    at D:\xampp\htdocs\qzzy\node_modules\@angular\compiler\bundles\compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (D:\xampp\htdocs\qzzy\node_modules\@angular\compiler\bundles\compiler.umd.js:12956:28)
    at analyzeNgModules (D:\xampp\htdocs\qzzy\node_modules\@angular\compiler\bundles\compiler.umd.js:12700:16)
    at analyzeAndValidateNgModules (D:\xampp\htdocs\qzzy\node_modules\@angular\compiler\bundles\compiler.umd.js:12704:20)

I'm opening this issue here ([as well as on their repo](https://github.com/driftyco/ionic-app-scripts/issues/786)) because I noticed you had an AoT commit, then partial revert, and I would like to know where does it currently stand?

**Comment by willsoto** [comment]
This has been a long ongoing issue. I feel like the state of AoT tooling isn't quite ready yet. I reverted the AoT stuff because it effectively broke the build for everyone, as opposed to just ionic users (which seem to be the primary reporters of AoT related issues.)

If someone can come up with a _clean_ solution, I'd be happy to take a look.

**Comment by AmitMY** [comment]
Thanks...
I think my only solution now is to revert to chart.js or implement chartist for angular myself.
I don't know about the state of AoT tooling, but hopefully something that you find ready.

**Comment by willsoto** [comment]
> implement chartist for angular myself.

I would imagine you are going to run into the same issues as I have, but if you do find a solution, feel free to let me know.
